name: 'temporal_features'
version: '1.0.0'

profile: 'temporal_features'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:  
  - "target"
  - "dbt_packages"

models:
  temporal_features:
    stage_view:
      materialized: view
      schema: "temporal_us"
    stage_table:
      materialized: table
    transform_temporal_features:
      description: "Transformation written in Python"
      materialized: table
      columns: ['store_number', 'vendor_number']
      window_lengths: [1, 7, 30]
      id_column: 'invoice_and_item_number'  
      date_column: 'date'
